name: Trigger a Satis rebuild

on: 
  push:
    branches: ["main", "release/main"]

  workflow_dispatch:  

jobs:

  satis:

    runs-on: ubuntu-latest

    steps:

    - name: Retrieve the repository name
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV      
    
    - name: Retrieve the branch name
      uses: nelonoel/branch-name@v1.0.1

    - name: Trigger Satis rebuild   
      uses: actions/github-script@v6        
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: '${GITHUB_REPOSITORY_OWNER}',
            repo: '${REPO_NAME}',
            workflow_id: 'cd.yml',
            ref: '${BRANCH_NAME}'
          })



