name: Trigger a Satis rebuild

on: 
  push:
    branches: ["release/main"]

  workflow_dispatch:  

jobs:

  satis:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Satis 
      uses: actions/github-script@v6
      env:
        SATIS_REPO_OWNER: ${{ vars.SATIS_REPO_OWNER }}
        SATIS_REPO_NAME: ${{ vars.SATIS_REPO_NAME }}
        SATIS_BUILD_WORKFLOW: ${{ vars.SATIS_BUILD_WORKFLOW }}
        SATIS_BUILD_BRANCH: ${{ vars.SATIS_BUILD_BRANCH }}          
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |          
          await github.rest.actions.createWorkflowDispatch({
            owner: `${SATIS_REPO_OWNER}`,
            repo: `${SATIS_REPO_NAME}`,
            workflow_id: `${SATIS_BUILD_WORKFLOW}`,
            ref: `${SATIS_BUILD_BRANCH}`
          })

          