name: Trigger a Satis rebuild

on: 
  push:
    branches: ["release/main"]

  workflow_dispatch:  

env:
  SATIS_REPO_OWNER: ${{ vars.SATIS_REPO_OWNER }}
  SATIS_REPO_NAME: ${{ vars.SATIS_REPO_NAME }}
  SATIS_BUILD_WORKFLOW: ${{ vars.SATIS_BUILD_WORKFLOW }}
  SATIS_BUILD_BRANCH: ${{ vars.SATIS_BUILD_BRANCH }}

jobs:

  satis:

    runs-on: ubuntu-latest

    steps:

    # - name: Retrieve the repository name
    #   run: |
    #     echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV      
    
    # - name: Retrieve the branch name
    #   uses: nelonoel/branch-name@v1.0.1

    - name: Debug
      run: |
        echo "'${{ vars.SATIS_REPO_OWNER }} ${{ vars.SATIS_REPO_NAME }} ${{ vars.SATIS_WORKFLOW }} ${{ vars.SATIS_BUILD_BRANCH }}'";

    - name: Trigger Satis rebuild   
      uses: actions/github-script@v6        
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: '${{ vars.SATIS_REPO_OWNER }}',
            repo: '${{ vars.SATIS_REPO_NAME }}',
            workflow_id: '${{ vars.SATIS_WORKFLOW }}',
            ref: '${{ vars.SATIS_BUILD_BRANCH }}'
          })



