name: Trigger a Satis rebuild

on: 
  push:
    branches: ["release/main"]

  workflow_dispatch:  

jobs:

  satis:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Satis 
      uses: actions/github-script@v6
      env:
        SATIS_REPO_OWNER: ${{ vars.SATIS_REPO_OWNER }}
        SATIS_REPO_NAME: ${{ vars.SATIS_REPO_NAME }}
        SATIS_BUILD_WORKFLOW: ${{ vars.SATIS_BUILD_WORKFLOW }}
        SATIS_BUILD_BRANCH: ${{ vars.SATIS_BUILD_BRANCH }}          
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |          
          await github.rest.actions.createWorkflowDispatch({
            owner: vars.SATIS_REPO_OWNER,
            repo: vars.SATIS_REPO_NAME,
            workflow_id: vars.SATIS_BUILD_WORKFLOW,
            ref: vars.SATIS_BUILD_BRANCH
          })

          
